name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Copy files over SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: 3.23.212.92
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ec2-user/ChawChaw2-front

      - name: Install and Build Next.js
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 3.23.212.92
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/ChawChaw2-front
            yarn install
            yarn build

      - name: Run Next.js application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 3.23.212.92
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/ChawChaw2-front
            pm2 start 0