name: Label main branch Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  label-main-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Label main branch Pull Requests
        if: github.event.pull_request.base.ref == 'main'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const number = context.issue.number;
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: number,
              labels: ['main']
            });