name: Label Merged in Dev Branch Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  label-dev-merged-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if PR branch is merged with dev
        id: check_merged
        uses: technote-space/git-merged@v1
        with:
          TARGET_BRANCH: dev
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label dev merged Pull Requests
        if: steps.check_merged.outputs.merged == 'true' && github.event.pull_request.base.ref == 'main'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const number = context.issue.number;
            
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: number,
              labels: ['dev']
            });
