name: Label Dev Merged Branches on Main PRs

on:
  push:
    branches:
      - dev

jobs:
  label-dev-merged-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Label Dev Merged Branches on Main PRs
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branch = context.ref.split('/').pop();

            if (branch !== 'dev') {
              return;
            }

            const { data: commits } = await github.rest.repos.listCommits({
              owner,
              repo,
              sha: branch
            });

            const mergedBranch = commits[0].commit.message.split(' ')[1].slice(1, -1);

            const { data: prs } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${mergedBranch}`,
              base: 'main'
            });

            if (prs.length > 0) {
              const mainPrNumber = prs[0].number;
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: mainPrNumber,
                labels: ['dev']
              });
            }